AWSTemplateFormatVersion: 2010-09-09
Parameters:
    DBAllocatedStorage:
        Default: '5'
        Description: The size of the database (Gb)
        Type: Number
        MinValue: '5'
        MaxValue: '6144'
    DBClass:
        Default: db.t3.micro
        Description: Database instance class
        Type: String
        ConstraintDescription: must select a valid database instance type.
Resources:
    Database:
        Type: AWS::RDS::DBInstance
        Properties:
            DBname: postgresql
            Engine: postgres
            AllocatedStorage: !Ref DBAllocatedStorage
            DBInstanceClass:
                Ref: DBClass
            MasterUsername: !Sub '{{resolve:ssm:/database/db/username}}'
            MasterUserPassword: !Sub '{{resolve:ssm:/database/db/password}}'
            PubliclyAccessible: false
    DatabaseSSM:
        Type: AWS::SSM::Parameter
        Properties:
        Name: !Join [ '', [ /database/, /db/url ] ]
        Type: String
        Value:
            Fn::Join:
            - ''
            - - jdbc:postgresql://
                - Fn::GetAtt:
                    - Database
                    - Endpoint.Address
                - ':'
                - Fn::GetAtt:
                    - Database
                    - Endpoint.Port
                - '/'
                - !Ref DBName

Outputs:
  DatabaseSSM:
    Value: !Ref DatabaseSSM