AWSTemplateFormatVersion: 2010-09-09
Parameters:
    DBAllocatedStorage:
        Default: '5'
        Description: The size of the database (Gb)
        Type: Number
        MinValue: '5'
        MaxValue: '6144'
    DBClass:
        Default: db.t3.micro
        Description: Database instance class
        Type: String
        ConstraintDescription: must select a valid database instance type.
Resources:
    Database:
        Type: AWS::RDS::DBInstance
        Properties:
            DBname: postgresql
            Engine: postgres
            AllocatedStorage: !Ref DBAllocatedStorage
            DBInstanceClass:
                Ref: DBClass
            MasterUsername: !Sub '{{resolve:ssm:/database/db/username}}'
            MasterUserPassword: !Sub '{{resolve:ssm:/database/db/password}}'
            PubliclyAccessible: false